apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationprofiles.kubescape.io
spec:
  group: kubescape.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              containers:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    execs:
                      type: array
                      items:
                        type: object
                        properties:
                          path:
                            type: string
                          args:
                            type: array
                            items:
                              type: string
                          envs:
                            type: array
                            items:
                              type: string
  scope: Namespaced
  names:
    plural: applicationprofiles
    singular: applicationprofile
    kind: ApplicationProfile
